#!/bin/bash

export TIMEFORMAT=%R
cd elixir/
mix compile.protocols
echo 'start timed run'
time elixir -pa _build/dev/consolidated -S mix mapreduce
time elixir -pa _build/dev/consolidated -S mix mapreduce
time elixir -pa _build/dev/consolidated -S mix mapreduce
time elixir -pa _build/dev/consolidated -S mix mapreduce
time elixir -pa _build/dev/consolidated -S mix mapreduce
